### PR TITLE
Miri 1177 lrs pathloss

### PR DESCRIPTION
**Pull request by JuergenSchreiber**
Added new LRS PATHLOSS datamodel to consider flux loss of point sources in slit mode depending on the position in the slit. Corresponding model is currently implemented in the JWST pipeline.

### CODE REVIEW

**Comment by smbeard** [comment]
The new data model itself looks fine to me. I added the new model to ancestry.py. At the moment I assume there is no equivalent JWST data model, so the entry can be commented out.

               'MiriLrsApertureCorrectionModel': 'MirLrsApcorrModel',
               'MiriMrsApertureCorrectionModel': 'MirMrsApcorrModel',
#                'MiriLrsPathlossCorrectionModel': '',
               'MiriBadPixelMaskModel' :    'MaskModel', \

I needed to merge master with this branch to resolve a conflict in ancestry.py, but it has now been corrected.
The branch looks fine to me. If you are happy with my change to ancestry.py you can go ahead and merge it.

**Review by smbeard — APPROVED** [review]

**Comment by JuergenSchreiber** [comment]
Actually, in the current jwst pipeline developer version there already is the LRS pathloss datamodel called
MirLrsPathlossModel
but I guess this should only be in ancestry when the it becomes next user release and integrated in miricle?

**Comment by smbeard** [comment]
> Actually, in the current jwst pipeline developer version there already is the LRS pathloss datamodel called MirLrsPathlossModel but I guess this should only be in ancestry when the it becomes next user release and integrated in miricle?

In which case I suggest you add the following line to ancestry.py before merging the branch:

`                'MiriLrsPathlossCorrectionModel': 'MirLrsPathlossModel ',
`

This entry in ancestry is used to define the DATAMODL keyword, which tells the JWST software which data model to use when opening a CDP file. We should make this change well before we deliver any pathloss CDP files to STScI, so it makes sense to do it now before we forget.

**Comment by JuergenSchreiber** [comment]
Thanks Steven

**Pull request merged**
