### PR TITLE
MIRI-749, MIRI-839, MIRI-759: update MiriTE to be based on JWST PL B7.4 

### PR DESCRIPTION
**Pull request by vcgeers**
Wim has now achieved a successful MIRICLE devel build based on JWST PL B7.4 with this branch (and corresponding branches of the other MIRI packages).

This PR is to bring to 'master' the required changes to update "MiriTE" to work with B7.4 of the JWST Pipeline (MIRI-749), and become part of the upcoming MIRISim 2.3.0 release (MIRI-839).

The changes include a re-structuring of the package by @smbeard to address MIRI-759. These structure changes were also separately implemented on branch "new_structure"; once this PR is merged, we can safely abandon/remove the "new_structure" branch.

Once these PRs are merged, I can update the MIRICLE devel build script to point back to 'master', from which point we should have our B7.4 based regular devel builds.

### CODE REVIEW

**Comment by vcgeers** [comment]
Since the moment that this branch was created from 'master', there have been a few changes committed to 'master' that are currently resulting in merge conflicts. I'll look into resolving these.

**Comment by vcgeers** [comment]
Just pushed a merge commit, merging the latest 'origin/master' into this branch.

You can click the link to the commit above to look at the resolution, but in summary, the only conflicts were:
- setup.py
- files that were newly added on 'master', these had to be moved to the appropriate directories on this branch

For the other (pre-existing) files, Git automatically applied changes that were done on 'master' to the same files in their new location (after the file move) as appropriate.

**Comment by smbeard** [comment]
You can go ahead and merge the branch into master, with one caveat. The resulting master branch will not be fully ready for the MIRISim 2.3.0 release (as described) because there the modifications made to address the subarray issues in MIRI-700 are still being tested on a branch test_scasim_subarrays.

The test_scasim_subarrays branch is still using build 7.3 and has the old repository structure. We will need to merge test_scasim_subarrays with testwithjwst0.15.0 , resolve any conflicts or issues due to the new structure or build 7.4, and then merge testwithjwst0.15.0 with master a second time. I think this will be a safer route than attempting to merge test_scasim_subarrays  directly into master, unless you think the merge conflicts will reappear.

**Comment by vcgeers** [comment]
Thanks Steven.

Indeed, I do not consider this "testwithjwst0.15.0" to be the only thing left to be done before the MIRISim 2.3.0 release; it is just the step to get us to B7.4.

After this PR is merged, I would prefer to use a new dedicated integration branch for bringing "test_scasim_subarrays" into the restructured 'master', to keep the purpose of each branch as focussed as possible. I can certainly help create such an integration branch.

**Pull request merged**
