### PR TITLE
Update jwst package imports to stdatamodels

### PR DESCRIPTION
**Pull request by eslavich**
In the upcoming 0.18.0 release of the jwst package, we're moving portions of the jwst.datamodels module to a separate package called [stdatamodels](https://github.com/spacetelescope/stdatamodels).  This PR updates imports in this repo to pull from stdatamodels where necessary.

I tested this with jwst master and stdatamodels master and the miri.datamodels tests all pass.  The is one test failure in another module:

```
FAILED miri/simulators/scasim/tests/test_detector.py::TestDetectorArray::test_frame_time - ValueError: cannot reshape array of size 34576272 into shape (2,200,1024,1032)
```
but I don't think that's related since it also fails on MiriTE master with jwst 0.17.1.

As written this PR breaks compatibility between this package and jwst 0.17.1.  Is that acceptable?

### CODE REVIEW

**Comment by smbeard** [comment]
Thank you for running those tests with the new stdatamodels package. It is good to know that everything within miri.datamodels works with your changes. It sounds like the problem with test_detector.py is unrelated. However, you are two steps ahead of the MIRI team at the moment. We are still testing the software with jwst 0.17.0 (see https://ukatcfaultlog.atlassian.net/browse/MIRI-944). The fault with test_detector.py is likely to show up in those tests.

I propose that we put this pull request on hold until the MIRI testing has caught up.  First the MIRI software is tested against 0.17.1 in a git branch and we correct the problem seen in test_detector.py. If those tests work the 0.17.1 test branch is merged with master. Then we create a branch to test the MIRI software against 0.18.0 and merge the changes you made here with that branch. If the combined changes work then we merge the 0.18.0 test branch with master.

**Comment by eslavich** [comment]
Thanks, that sounds good!  We would like to release stdatamodels soon, so we were mainly interested to see if we could get this package working with our release candidate.  It looks like that won't be a problem.

**Comment by smbeard** [comment]
I think I may have solved the problem which caused test_detector.py to fail, although we won't know for sure until my changes are tested with this branch. The test_frame_time function tests that SCASim calculates the correct frame time for a number of simulated detectors of different shapes and sizes. If the time matches the value listed in Mike Ressler's table the test passes. I discovered all the CDP files associated with these test detector objects were being opened and read, even though they are not used. My change prevents these unnecessary CDPs from being opened, which should reduce the memory requirement. It looks like your error happened when this test attempted to read a DARK CDP for an odd-sized detector, and this should no longer happen.

**Comment by vcgeers** [comment]
@eslavich, thank you very much for this PR.

We've just started testing MIRICLE against Pipeline B7.7 (https://ukatcfaultlog.atlassian.net/browse/MIRI-949). To allow us to test these (backward-incompatible) changes, and make further fixes, I've created a new integration branch off of 'master', and redirected this PR to the new branch.

I'll merge this into the integration branch, and open a new PR for MIRI team to continue testing.

**Pull request merged**
