### PR TITLE
MIRI-749: updated setup.py with required dependencies.

### PR DESCRIPTION
**Pull request by vcgeers**
Wim and I are working on updating MIRICLE to include the new JWST PL B7.4 (i.e. 0.15.1). One change we want to add is for the setup.py files to declare the dependencies explicitly. See:
https://ukatcfaultlog.atlassian.net/browse/MIRI-749

This pull request updates the setup.py file with the dependencies that I believe "miri" (aka MiriTE) needs. I have pinned the versions to a minimum, and picked at least the minimum that was present in the MIRISim 2.2.0 release, or newer if that was present in the B7.4 release.

I also removed an unused import of "numpy" from the setup.py file.

I'm first merging this into the existing "testwithjwst0.15.0" branch, since that was already being used to test against JWST B7.4. I pinned "jwst" to >=0.15.0, since this branch was primarily tested against 0.15.0 (some B7.4 release candidate), but we probably want to increase that to "0.15.1" (the final B7.4 release) once we've confirmed that this branch is also still compatible with 0.15.1.

### CODE REVIEW

**Comment by smbeard** [comment]
The changes to setup.py look straightforward. I tried the new branch using the conda environment I created for testing the testwithjwst0.15.0 branch in the first place. When I built the MIRI software with the command "python setup.py install" the installation procedure installed the software as normal and finished by processing the dependencies. This resulted in a lot of messages looking like this numpy example:

> Using /sw/sw4/smb/anaconda3/envs/jwsttest/lib/python3.7/site-packages
> Searching for numpy==1.18.1
> Best match: numpy 1.18.1
> Adding numpy 1.18.1 to easy-install.pth file
> Installing f2py script to /sw4/smb/anaconda3/envs/jwsttest/bin
> Installing f2py3 script to /sw4/smb/anaconda3/envs/jwsttest/bin
> Installing f2py3.7 script to /sw4/smb/anaconda3/envs/jwsttest/bin

The extra steps don't seem to harm the installation (it passed a self-test), but I noticed that the ">=" notation causes the script to install the very latest version of a package when the correct version is not found in the conda environment. This might cause side effects for someone installing the MiriTE package in an ad-hoc environment but should be ok if we can be sure the jwst software (or MIRICLE) has been installed first.

I recommend that the entries for paramiko and pysftp be changed from >= to ==. I remember while developing the CDP fetching software that having these exact versions is critical.

**Comment by smbeard** [comment]
By the way, paramiko and pysftp should have entries

paramiko==2.7.1
pysftp==0.2.9

not >=2.6.0

**Comment by vcgeers** [comment]
Steven, I can pin the version for 'paramiko' and 'pysftp'. On the upside, these do not seem to be used by other packages, so it is less likely that we get into a version conflict in the future (though it could happen through shared 3rd party dependencies).

W.r.t. 'paramiko' though, you mention "==2.7.1", but it appears that our most recent stable MIRICLE release (with MIRISim 2.2.0) is installing "2.6.0". Could you confirm where the newer 2.7.1 comes from?

-

In the meantime, I've added two more dependencies to the setup, 'numba' and 'parameterized', which are needed by certain test modules.

**Comment by smbeard** [comment]
> W.r.t. 'paramiko' though, you mention "==2.7.1", but it appears that our most recent stable MIRICLE release (with MIRISim 2.2.0) is installing "2.6.0". Could you confirm where the newer 2.7.1 comes from?

Now you mention it, I activated the miricle.devel environment and, indeed, the version of paramiko found there is 2.6.0. But when I switch to the jwsttest environment I use to test the testwithjwst0.15.0 branch I notice paramiko 2.7.1 is installed. This might have been an accidental side-effect of running the installation script in an environment where paramiko is not available: it installed the latest version.

I don't think the actual version number matters so much, as long as a particular version is thoroughly tested before release and then locked. Some of the paramiko releases in the past have not been backwards compatible or have depended on a specific version of pysftp, so it's best to keep both of those packages version-locked.

**Comment by vcgeers** [comment]
Thanks Steven.

Perhaps for the "testwithjwst0.15.0", Wim might have just up-versioned some packages to continue to stay up-to-date as much as possible.

It is indeed the intent that our MIRICLE builds (especially stable and test) will run the full suite of unit tests and if those pass, then the build will released with locked versions. So I think that should address what you said, without needing to hard-locking the versions within the setup file itself, would you agree?

If so, any objections to me merging this into the testwithjwst0.15.0 branch? (i.e. merging this PR)

**Comment by smbeard** [comment]
> It is indeed the intent that our MIRICLE builds (especially stable and test) will run the full suite of unit tests and if those pass, then the build will released with locked versions. So I think that should address what you said, without needing to hard-locking the versions within the setup file itself, would you agree?

That's true for MIRI developers who have installed MIRICLE but not for CAP software developers who have elected to install the JWST software and add MiriTE as an extra package within that environment. There shouldn't be a problem with packages that are already available within the JWST release, but there can be a problem with packages that are unique to MiriTE.

> If so, any objections to me merging this into the testwithjwst0.15.0 branch? (i.e. merging this PR)

No objection to merging the branch, but I recommend that paramiko and pysftp be locked to specific versions to reduce the risk of CAP software no longer working because of an unexpected paramiko release during commissioning. I think in this case we lock the versions unless a future bug is raised, rather than the other way round.

**Comment by vcgeers** [comment]
Ok, thanks. Then I'll push another update to lock those two packages, and I'll lock paramiko to the earlier 2.6.0, since that's the one we've already tested against for a stable MIRICLE release.

After this, I'll merge the request, and let Wim know that he can start pointing the new MIRICLE build to the testwithjwstt0.15.0 branch (instead of this branch).

**Pull request merged**
